#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     rightBack,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightFront,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     armMotor,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     leftFront,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     leftBack,      tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    goalGrabber,          tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    bucketSwod,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_3,    drawerSlide,          tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    grabberMover,         tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main ()
{
	nMotorEncoder[ArmMotor] = 0;

	motor[armMotor] =40;
	while(nMotorEncoder[ArmMotor] < 10) { // while the Motor Encoder of Motor B doesn't reach 360 ticks:
	}
	motor[armMotor] = 0;
}
