#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorArm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servoQuarter,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servoSBOD,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servoDock,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"     // Tells ROBOTC to include the driver file for the joystick.

task main()
{
	while (true) {

    	getJoystickSettings(joystick);  // Update Buttons and Joysticks

    	if (joy1Btn(1)) {                  // If Joy1-Button1 is pressed:
    		servo[servoSBOD] = 200;              // Turn the servo On continuously
    	} else {                          // If Joy1-Button1 is NOT pressed:
    		servo[servoSBOD] = 127;                 // Stop the servo
    	}
	}
}
