#pragma config(Hubs,  S1, HTMotor,   none,   none,   none)
#pragma config(Hubs,  S1, HTMotor,   none,   none,   none)
#pragma config(Sensor, S2,     IRSeeker,       sensorNone)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorRight,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorRight,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "lib\sensors\drivers\hitechnic-irseeker-v2.h"
#include "lib\ir_utils.h"


typedef enum dir {
	right,
	left,
	center,
} direction;

direction get_dir_to_beacon(void)
{
	int segment;

	segment = HTIRS2readACDir(irSeeker);

	switch (segment){
	case 1:
	case 2:
	case 3:
	case 4:
		return left;
		break;

	case 5:
		return center;
		break;

	case 6:
	case 7:
	case 8:
	case 9:
		return right;
		break;
	}

	return right;
}

task main()
{
	direction dir;
	int strength;

	tHTIRS2DSPMode mode = DSP_1200
	HTIRS2setDSPMode(IRSeeker, mode);

	while(true){

		strength = get_ir_strength(IR_STRENGTH_3);

		if (dir == right) {
			motor[driveLeft] = 50;
			motor[driveRight] = -50;
		} else if (dir == left) {
			motor[driveLeft] = -50;
			motor[driveRight] = 50;
		} else if (dir == center) {
			motor[driveLeft] = 50;
			motor[driveRight] = 50;
		}
	}
}
